pipeline:
  sonar-scanner:
    image: aosapps/drone-sonar-plugin
    secrets: [sonar_host, sonar_token]
    sources: iMXDemo
    when:
      event:
        - push
        - pull_request  
  build:
    image: tlwt/yoctodocker:latest
    secrets: [ GITHUB_TOKEN ]
    environment:
       - GIT_EMAIL=till.witt@nxp.com
       - GIT_NAME=Till Witt
       - Y_MACHINE=imx6ulevk
       - Y_DISTRO=fsl-imx-x11
       - Y_IMAGE=core-image-base

  slack: # pushing out notification
    image: plugins/slack:latest
    channel: build-automation
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
