pipeline:

  release:
    image: tlwt/yoctodocker
    secrets: [ GITHUB_TOKEN ]
    environment:
       - GIT_EMAIL=till.witt@nxp.com
       - GIT_NAME=Till Witt
       - Y_MACHINE=imx6ulevk
       - Y_DISTRO=fsl-imx-x11
       - Y_IMAGE=core-image-base
    commands:
       - pwd
       - ls ./data/
       - ls ./data/build_imx6ulevk/
       - ls ./data/build_imx6ulevk/tmp/
       - ls ./data/build_imx6ulevk/tmp/deploy/
       - ls ./data/build_imx6ulevk/tmp/deploy/images/
       -
       - d=$(date +%Y%m%d_%H%M%S)
       - releasename="img--$Y_DISTRO--$Y_MACHINE--$d.zip"
       - echo $releasename
       - zip "$releasename" ./data/build_$Y_MACHINE/tmp/deploy/images/*
       - github-release upload --owner tlwt --repo yoctoDocker --tag "$Y_DISTRO-$Y_MACHINE-$d" --name "$Y_DISTRO - $Y_MACHINE ($d)" --body "Yocto Build results" "$releasename" "./data/log_bake.txt" "./data/log_setup.txt"

  slack: # pushing out notification
    image: plugins/slack:latest
    channel: build-automation
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
