version: '3'

services:
   compiler:
     build: .
     stdin_open: true
     tty: true
     environment:
       - GIT_EMAIL=till.witt@nxp.com
       - GIT_NAME=Till Witt
       - Y_MACHINE=imx6ulevk
       - Y_DISTRO=fsl-imx-x11
       - Y_IMAGE=core-image-base
     volumes:
       - ./data:/data
       - ./:/repo/yoctoDocker
